### ISSUE TITLE
Ubuntu PPA?

### ISSUE THREAD

**Issue by domacikolaci** [orhun/pkgtop#13]
Hi,

Any chance of getting this on an Ubuntu PPA? 

Not sure what's involved in getting this to happen but would be a nice thing for noobs like me to get this working and maintained on our systems :)

**Comment by keylo99** [comment]
Hey,
I actually don't know how ubuntu ppa works now but I'll check that for creating a package for pkgtop.
Thanks for the suggestion.

**Comment by dawidd6** [comment]
@keylo99 I see you submitted ITP bug to Debian for pkgtop.

Just wanted to say that if you need some help with packaging or other Debian related quirks, just ping me here or via email. I have experience with packaging Go software for Debian and also for Ubuntu via PPAs.

**Comment by keylo99** [comment]
I need help with the uploading actually. Some tools are not working for me since I'm using Arch Linux. So what can I do now?

**Comment by dawidd6** [comment]
Which tools? At what state are you now? Give some details.

**Comment by keylo99** [comment]
I'm using `dh-make-golang` tool for creating a debian package from my golang source. I've handled the TODOs and other the ITP stuff as you see. Now I'm trying to build the package with the `gbp buildpackage --git-pbuilder` command but I don't have the `pbuilder` or `cowbuider`(?) installed so I'm stuck at this state.
(I forgot to give details bc I was kind of zoned out, sorry.)

**Comment by dawidd6** [comment]
Looks like `pbuilder-ubuntu` is in AUR, you can use that.
