### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by gombosg** [orhun/pkgtop#17]
Hi, I'm a Fedora packager. I'm keeping an eye on the project and will try to get it into Fedora once it matures a bit. It requires submitting the [`termui`](https://github.com/gizak/termui/) package and this one, but both seem to be fairly simple.

**Comment by keylo99** [comment]
Hey, 
Currently I'm fixing the issues and adding requested Linux distributions. I'd be glad if you make a Fedora package for the project. :+1:
