### ISSUE TITLE
text looks strange

### ISSUE THREAD

**Issue by zany130** [orhun/pkgtop#28]
is the text supposed to look like this in the bottom?
![Screenshot_20200906_215340](https://user-images.githubusercontent.com/25832539/92341411-99d1b800-f08b-11ea-941e-d7ff9eaeb39f.png)

**Comment by orhun** [comment]
Yes, it is how it supposed to look. It's basically showing the executed commands.

**Comment by zany130** [comment]
then that is unsable for anyone i just opend pkgtop and i get all that garbage in the bottom with print f and buch of other stuff. Shouldt the controls be there
