### ISSUE TITLE
Error on start.

### ISSUE THREAD

**Issue by Anonymous2716** [orhun/pkgtop#30]
In termux (Android)
```
~ $ pkgtop
2022/12/13 23:54:53 Execution of 'sh' failed with exit status 2
```

Version: 2.4.1

**Comment by orhun** [comment]
Oh really, dang. Well in this case we need to run each package manager command (defined [here](https://github.com/orhun/pkgtop/blob/master/cmd/pkgtop.go#L48)) to see what's going wrong.

**Comment by Anonymous2716** [comment]
@orhun alright.

**Comment by Anonymous2716** [comment]
It seemed to work with 
```
pkgtop -d debian
```

bcs termux environment is debianlike.

**Comment by Anonymous2716** [comment]
@orhun  the issue was with the distribution check which pkgtop gets from standard Linux paths/files and termux package maintainers patched the program and its been fixed.  

Here:

https://github.com/termux/termux-packages/tree/master/packages/pkgtop

Closing this issue.
