### ISSUE TITLE
[Suggestion] AUR Package Support

### ISSUE THREAD

**Issue by nlogozzo** [orhun/pkgtop#5]
Can you add support for installing packages from the air via helpers such as yay

**Comment by keylo99** [comment]
I don't quite get it. There's a AUR package available [here](https://aur.archlinux.org/packages/pkgtop-git/) and you can install pkgtop with AUR package managers.
```
[k3@arch ~]$ yay pkgtop
2 aur/pkgtop 1.3-1 (+1 0.99%) 
    Interactive package manager & resource monitor (stable version)
1 aur/pkgtop-git r340.10ff101-1 (+4 3.89%) (Installed: r339.841a201-1)
    Interactive package manager & resource monitor
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 

```

**Comment by Tajnymag** [comment]
@keylo99 I believe nlogozzo by AUR support means listing and installing packages FROM the AUR.

Right now it seems that pkgtop allow installation of official packages only.

**Comment by keylo99** [comment]
Oh, my bad.
Like @Tajnymag said pkgtop only allows installing official packages.
But I'm thinking of adding a option for the package management tool.  So, thanks for the suggestion.
